"use strict";
const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");
const root=path.resolve(__dirname,"..","..");const media=require(path.join(root,"media-resolver.js"));const importer=require(path.join(root,"catalog-importer.js"));const updater=require("../catalog-update-core.js");const rakuten=require("../adapters/rakuten-adapter.js");const ebay=require("../adapters/ebay-adapter.js");
global.window={PriceAlertImporter:importer};require(path.join(root,"products.js"));const products=global.window.PriceAlertData.products;
assert.equal(products.length,100,"development catalog contains 100 products");assert.equal(new Set(products.map(p=>p.id)).size,100);assert.equal(new Set(products.map(p=>p.slug)).size,100);assert.ok(products.every(p=>p.id&&p.slug&&p.brand&&p.name&&p.category));
const added=products.filter(p=>!p.offers.length);assert.equal(added.length,84);assert.ok(added.every(p=>p.identity.upc===null&&p.identity.gtin===null&&p.identity.mpn===null),"new identities do not fabricate trade identifiers");assert.ok(added.every(p=>p.priceHistory.length===0),"new identities do not fabricate price history");

const base={primaryImage:"https://images.invalid/product.jpg",imageSource:"approved-source",sourceApproved:true};
for(const type of ["scraped","google-images","search-engine","arbitrary-web","unknown","unverified","hotlinked-unapproved"]){assert.equal(media.normalizeMedia({...base,imageSourceType:type}).primaryImage,null,`${type} rejected`);}
for(const type of ["affiliate-feed","affiliate-api","retailer-feed","retailer-api","manufacturer-authorized-feed","manufacturer-api","licensed","owned","public-domain"]){assert.equal(media.normalizeMedia({...base,imageSourceType:type}).primaryImage,"https://images.invalid/product.jpg",`${type} accepted when explicitly approved`);}
assert.equal(media.normalizeMedia({...base,sourceApproved:false,imageSourceType:"affiliate-api"}).primaryImage,null,"HTTPS without approval fails closed");
const aliases=media.normalizeMedia({imageurl:"https://images.invalid/main.jpg",additional_image_link:["https://images.invalid/2.jpg"],thumbnail:"https://images.invalid/thumb.jpg",imageSourceType:"affiliate-feed",imageSource:"feed",sourceApproved:true});assert.equal(aliases.primaryImage,"https://images.invalid/main.jpg");assert.deepEqual(aliases.galleryImages,["https://images.invalid/2.jpg"]);assert.equal(aliases.thumbnail,"https://images.invalid/thumb.jpg");
const attributes={},placeholder={hidden:true,setAttribute:(key,value)=>attributes[`placeholder-${key}`]=value},container={dataset:{mediaKind:"image"},querySelector:()=>placeholder,setAttribute:(key,value)=>attributes[key]=value},broken={hidden:false,alt:"Synthetic product",closest:()=>container,removeAttribute:key=>attributes[`removed-${key}`]=true};assert.equal(media.fallbackImageElement(broken,"Synthetic product"),true);assert.equal(broken.hidden,true);assert.equal(placeholder.hidden,false);assert.equal(container.dataset.mediaKind,"placeholder");assert.equal(attributes["removed-src"],true);

const existing={id:"existing",familyId:"existing",brand:"Known",name:"Known Product",modelNumber:"M-1",identity:{brand:"Known",manufacturer:"Known",modelNumber:"M-1",upc:"123456789012"},specifications:{},variants:[{variantId:"v1",storage:"1 TB",isDefaultVariant:true}],offers:[],priceHistory:[],media:null};
const incoming=importer.normalizeProduct({id:"incoming",brand:"Known",name:"Known Product",modelNumber:"M-1",upc:"123456789012",variants:[{variantId:"incoming-v",storage:"1 TB",isDefaultVariant:true}],primaryImage:"https://images.invalid/approved.jpg",imageSourceType:"manufacturer-authorized-feed",imageSource:"manufacturer-feed",sourceApproved:true}).product;
const merged=updater.updateCatalog([existing],[incoming]);assert.equal(merged.report.updated,1);assert.equal(merged.products[0].media.primaryImage,"https://images.invalid/approved.jpg","UPC match attaches authorized image");
const byModel=media.attachToCatalog([existing],{...incoming,upc:null,gtin:null,identity:{...incoming.identity,upc:null,gtin:null,manufacturer:"Known",modelNumber:"M-1"},specifications:{...incoming.specifications,upc:null,gtin:null}},updater.matchProducts);assert.equal(byModel.attached,true);assert.equal(byModel.matchedBy,"manufacturer-model");
const conflict=updater.updateCatalog([existing],[{...incoming,variants:[{variantId:"incoming-v",storage:"2 TB",isDefaultVariant:true}]}]);assert.equal(conflict.report.conflicts,1,"variant mismatch cannot overwrite media");

const rakutenResult=rakuten.normalize([{id:"rakuten-record",productname:"Approved Feed Product",sku:"MODEL-1",upccode:"123456789012",imageurl:"https://images.invalid/rakuten.jpg",offers:[]}],importer,{sourceApproved:true,sourceType:"affiliate-feed",sourceId:"approved-rakuten-advertiser",dataStatus:"sample-development"});assert.equal(rakutenResult.products[0].media.primaryImage,"https://images.invalid/rakuten.jpg");assert.equal(rakutenResult.products[0].media.imageSourceType,"affiliate-feed");
const rakutenRejected=rakuten.normalize([{id:"rakuten-rejected",productname:"Unapproved Product",imageurl:"https://images.invalid/no.jpg",offers:[]}],importer,{sourceApproved:false,sourceType:"affiliate-feed",dataStatus:"sample-development"});assert.equal(rakutenRejected.products[0].media.primaryImage,null);
const ebayResult=ebay.normalize([{id:"ebay-record",brand:"Known",name:"eBay API Product",modelNumber:"E1",image:{imageUrl:"https://images.invalid/ebay-main.jpg"},additionalImages:[{imageUrl:"https://images.invalid/ebay-2.jpg"}],offers:[]}],importer,{sourceApproved:true,sourceType:"retailer-api",sourceId:"approved-ebay-browse",dataStatus:"sample-development"});assert.equal(ebayResult.products[0].media.primaryImage,"https://images.invalid/ebay-main.jpg");assert.deepEqual(ebayResult.products[0].media.galleryImages,["https://images.invalid/ebay-2.jpg"]);

const app=fs.readFileSync(path.join(root,"app.js"),"utf8"),page=fs.readFileSync(path.join(root,"products","index.html"),"utf8"),detail=fs.readFileSync(path.join(root,"products","dewalt-dcd771c2","product-page.js"),"utf8");assert.match(app,/Retailer pricing/);assert.match(app,/View product details/);assert.match(app,/fallbackProductImage/);assert.match(detail,/product-gallery/);assert.match(detail,/useMediaFallback/);assert.match(page,/id="compare-offers-control" aria-disabled="true">Retailer offers coming soon/);assert.match(detail,/if \(bestOffer\)[\s\S]*Compare retailer offers/);assert.match(detail,/href="#retailer-offers"/);
console.log("100-product catalog, authorized media, adapters, matching, variants, and no-price UI tests passed.");
